# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-19 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracked_auction',
            fields=[
                ('auction_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(default=-1)),
                ('owner', models.CharField(max_length=200)),
                ('buyout', models.IntegerField(default=-1)),
                ('quantity', models.IntegerField(default=-1)),
                ('time_class', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
