# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-21 23:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowapi_app', '0002_tracked_auction_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracked_auction',
            old_name='auction_id',
            new_name='auc',
        ),
        migrations.RenameField(
            model_name='tracked_auction',
            old_name='item_id',
            new_name='item',
        ),
    ]
