# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-21 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wowapi_app', '0003_auto_20161222_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracked_auction',
            old_name='time_class',
            new_name='timeLeft',
        ),
    ]
