# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-22 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowapi_app', '0004_auto_20161222_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_history',
            fields=[
                ('auc', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=-1)),
                ('owner', models.CharField(max_length=200)),
                ('buyout', models.IntegerField(default=-1)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(auto_now_add=True)),
                ('end_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Auction_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField(default=-1)),
                ('buyout', models.IntegerField(default=-1)),
                ('sold', models.IntegerField(default=0)),
                ('expired', models.IntegerField(default=0)),
                ('relisted', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='auction_stats',
            unique_together=set([('item', 'buyout')]),
        ),
    ]
