# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowapi_app', '0005_auto_20161222_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.IntegerField(default=1482685189000)),
            ],
        ),
    ]
